version: '3'
services:
  movie-api:
    build: .
    ports:
      - 6060:6060
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=movie-db;Database=MovieDb;User=sa;Password=S0up3dUpPassword;
      - ASPNETCORE_URLS=https://+:6060
      - ASPNETCORE_HTTPS_PORT=6060
      - ASPNETCORE_Kestrel__Certificates__Default__Password=sanguine
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - movie-db
    volumes:
      - ~/.aspnet/https:/https:ro
  movie-db:
    build:
      context: .
      dockerfile: SqlServerDockerfile
    ports:
      - 1433:1433
    environment:
      - DB_HOST=movie-db